### ISSUE TITLE
Câu 3: Liệt kê các chân điều khiển tín hiệu Digital trên Arduino?

### ISSUE THREAD

**Issue by DuyThanh36** [DuyThanh36/Lop-11A09-Nhom-01#12]

**Comment by TrungKien1508** [comment]
Các chân điều khiển tín hiệu Digital trên Arduino gồm 14 chân từ 0 đến 13. Các chân này sử dụng cho cả đầu vào/ đầu ra digital. Đặc biệt chân ~3 ~5 ~6 ~9 ~10 ~11 còn có thể sử dụng là đầu ra cho tín hiệu Analog.

**Comment by DuyThanh36** [comment]
Rất tốt Rất tốt.
