### ISSUE TITLE
Ý kiến về cách lắp mạch

### ISSUE THREAD

**Issue by DuyThanh36** [DuyThanh36/Lop-11A09-Nhom-01#17]
Đây là diễn đàn mọi người ngồi lại và bàn về cách để lắp mạch điện nháy nháy được giao trên tinkercad và đặc biệt llà phương pháp lập trình. Xin mọi người giúp đỡ. Cảm ơn.

**Comment by DuyThanh36** [comment]
@ThienPhuc33 @TrungKien1508 @hung0705 @HoangDaoMinhKhoi-23 Nhớ làm cái tinkercad trước nha mn

**Comment by DuyThanh36** [comment]
R khi nào làm xong có thể cap màn hình lên đây để cùng nhau hội ý

**Comment by DuyThanh36** [comment]
![Screenshot (122)](https://user-images.githubusercontent.com/91962681/141643392-c43595fb-0716-41fe-adac-7f1eb06e7e50.png)

**Comment by DuyThanh36** [comment]
Alo alo

**Comment by DuyThanh36** [comment]
Có j bên nhóm mình sẽ làm vào tầm 1h để mn còn làm việc khác nha. Mọi người nhớ canh h để vô làm chung vs mọi người.

**Comment by DuyThanh36** [comment]
@ThienPhuc33 @hung0705 @HoangDaoMinhKhoi-23 Hội ý này mn

**Comment by HoangDaoMinhKhoi-23** [comment]
thầy có dặn là bài này mình cần dùng arduino r3,resistor,đèn led và viết thêm code

**Comment by DuyThanh36** [comment]
Wtf

**Comment by DuyThanh36** [comment]
Làm xong cái mạch chưa mn

**Comment by HoangDaoMinhKhoi-23** [comment]
thiếu @TrungKien1508 mn cùng làm chung

**Comment by TrungKien1508** [comment]
![z2933246469461_1e1c42f2c8dd781639ec45b723b91a08](https://user-images.githubusercontent.com/91965600/141669770-35cb7ccf-e1f9-45de-9e76-3957b27f29b4.jpg)

**Comment by TrungKien1508** [comment]
làm vậy đúng ko mn

**Comment by DuyThanh36** [comment]
Tưởng làm 1 đền :))

**Comment by TrungKien1508** [comment]
Làm 3 đèn mà Thanh

**Comment by hung0705** [comment]
Có ai nối thử chưa vậy?

**Comment by TrungKien1508** [comment]
mn làm tới đâu rồi

**Comment by TrungKien1508** [comment]
giờ nhập code sao đây mn

**Comment by HoangDaoMinhKhoi-23** [comment]
![image](https://user-images.githubusercontent.com/91971080/141670008-1bcee866-b817-4e3e-b08c-a5121254082a.png)

**Comment by HoangDaoMinhKhoi-23** [comment]
tới phần viết code r bro

**Comment by hung0705** [comment]
Tui cũng vậy :>

**Comment by ThienPhuc33** [comment]
mng chia ra suy nghĩ code đi nào

**Comment by DuyThanh36** [comment]
![Screenshot (128)](https://user-images.githubusercontent.com/91962681/141670119-e32dad4e-69f5-4e43-8136-18a71cb82a56.png)

**Comment by DuyThanh36** [comment]
Ok chưa mn

**Comment by hung0705** [comment]
Ok rồi đó 👍

**Comment by DuyThanh36** [comment]
Ok v bắt đầu nghĩ code đi

**Comment by ThienPhuc33** [comment]
![image](https://user-images.githubusercontent.com/91963055/141670163-e911a277-a6b9-48d1-ab9b-7e4277425800.png)

**Comment by ThienPhuc33** [comment]
mng ơi

**Comment by ThienPhuc33** [comment]
nối lại đi

**Comment by ThienPhuc33** [comment]
tớ được rồi nè

**Comment by ThienPhuc33** [comment]
![image](https://user-images.githubusercontent.com/91963055/141670761-b0f5e4ea-9056-4632-afc0-4afb119b3596.png)

**Comment by DuyThanh36** [comment]
Có code chưa mn???

**Comment by ThienPhuc33** [comment]
mở đầu nhè mng

**Comment by ThienPhuc33** [comment]
void setup()
{
pinMode(13, OUTPUT);
pinMode(12, OUTPUT);
pinMode(11,OUTPUT)’
}

**Comment by HoangDaoMinhKhoi-23** [comment]
t làm void setup cho

**Comment by HoangDaoMinhKhoi-23** [comment]
void setup()
{
  pinMode(13, OUTPUT);
  pinMode(12, OUTPUT);
  pinMode(11, OUTPUT);
}

**Comment by HoangDaoMinhKhoi-23** [comment]
làm giống nhau nè phúc

**Comment by DuyThanh36** [comment]
Hay lắm

**Comment by ThienPhuc33** [comment]
ủa v hả
thật là trùng hợp

**Comment by DuyThanh36** [comment]
V @hung0705 Làm phần đèn đỏ đc ko

**Comment by hung0705** [comment]
> void setup()
> 
> {
> 
> pinMode(13, OUTPUT);
> 
> pinMode(12, OUTPUT);
> 
> pinMode(11,OUTPUT)’
> 
> }
> 
> 
Bạn làm sai rồi cái đó kết thúc phải là dấu chấm phẩy ấy

**Comment by DuyThanh36** [comment]
Để t suy nghĩ phần đèn xanh coi sao

**Comment by HoangDaoMinhKhoi-23** [comment]
void loop()
{

**Comment by DuyThanh36** [comment]
> > void setup()
> > {
> > pinMode(13, OUTPUT);
> > pinMode(12, OUTPUT);
> > pinMode(11,OUTPUT)’
> > }
> 
> Bạn làm sai rồi cái đó kết thúc phải là dấu chấm phẩy ấy 🥲

Tệ thế cơ

**Comment by HoangDaoMinhKhoi-23** [comment]
> > void setup()
> > {
> > pinMode(13, OUTPUT);
> > pinMode(12, OUTPUT);
> > pinMode(11,OUTPUT)’
> > }
> 
> Bạn làm sai rồi cái đó kết thúc phải là dấu chấm phẩy ấy 🥲

hưng nói đúng r đấy sửa đi bro

**Comment by HoangDaoMinhKhoi-23** [comment]
> void loop() {

tiếp theo là đèn đỏ

**Comment by hung0705** [comment]
void loop()
{
  digitalWrite(13, HIGH);
  delay(2000);
  digitalWrite(13, LOW);
  delay(1000);
Tui nghĩ code của đèn đỏ là như thế này mọi ng thấy sao

**Comment by DuyThanh36** [comment]
T nghĩ ko cần cái wait đâu ha

**Comment by DuyThanh36** [comment]
Sau cái // là chú thích hay j á

**Comment by DuyThanh36** [comment]
Nên ko cần đâu

**Comment by DuyThanh36** [comment]
@TrungKien1508 Làm cái phần đèn vàng đc ko??

**Comment by TrungKien1508** [comment]
digitalWrite(12, HIGH);
delay(2000);
digitalWrite(12, LOW);
delay(1000);

**Comment by DuyThanh36** [comment]
V để t chốt cái đèn xanh ha

**Comment by TrungKien1508** [comment]
okkk

**Comment by DuyThanh36** [comment]
digitalWrite(11, HIGH);
  delay(2000); 
  digitalWrite(11, LOW);
  delay(1000);

**Comment by DuyThanh36** [comment]
V là xong r đúng ko mn

**Comment by DuyThanh36** [comment]
À nhớ thêm cái "}" để kết thúc cái loop nha mn

**Comment by hung0705** [comment]
Oke v tui tổng hợp lại toàn bộ code nãy giờ mọi người nhắn nha

**Comment by DuyThanh36** [comment]
Nhớ phần đã sửa nha

**Comment by TrungKien1508** [comment]
okokok

**Comment by hung0705** [comment]
void setup()
{
pinMode(13, OUTPUT);
pinMode(12, OUTPUT);
pinMode(11,OUTPUT);
}
void loop()
{
  digitalWrite(13, HIGH);
  delay(2000);
  digitalWrite(13, LOW);
  delay(1000);
  digitalWrite(12, HIGH);
  delay(2000);
  digitalWrite(12, LOW);
  delay(1000);
  digitalWrite(11, HIGH);
  delay(2000);
  digitalWrite(11, LOW);
  delay(1000);
}

**Comment by DuyThanh36** [comment]
Ơ kìa

**Comment by DuyThanh36** [comment]
Sao ko đc ta

**Comment by HoangDaoMinhKhoi-23** [comment]
chưa đc

**Comment by DuyThanh36** [comment]
Có khi nào code sai ko ta

**Comment by HoangDaoMinhKhoi-23** [comment]
code đúng mà nhỉ

**Comment by TrungKien1508** [comment]
mn thử kiểm tra lại mach coi

**Comment by DuyThanh36** [comment]
Đúng mà

**Comment by ThienPhuc33** [comment]
mng ơi. mạch nãy sai r nhé. mình đã sửa lại mạch. mng tham khảo

**Comment by ThienPhuc33** [comment]
![image](https://user-images.githubusercontent.com/91963055/141671565-097561bd-500c-4b2e-af47-e0dd594f37a6.png)

**Comment by DuyThanh36** [comment]
> mng ơi. mạch nãy sai r nhé. mình đã sửa lại mạch. mng tham khảo

Sao m bik hay v

**Comment by DuyThanh36** [comment]
Copy của ai ko đó :)))

**Comment by ThienPhuc33** [comment]
copy từ cái đầu ra bạn ạ

**Comment by DuyThanh36** [comment]
Ghê v

**Comment by DuyThanh36** [comment]
V mn sửa lại cái mạch nha

**Comment by HoangDaoMinhKhoi-23** [comment]
> Ghê v

que

**Comment by ThienPhuc33** [comment]
=)))))

**Comment by DuyThanh36** [comment]
Ơ kìa

**Comment by HoangDaoMinhKhoi-23** [comment]
![image](https://user-images.githubusercontent.com/91971080/141671929-7ab2a899-678c-457c-8d38-fe1453aecaeb.png)
đc r,good lắm phúc

**Comment by hung0705** [comment]
Tui cũng làm được rồi cảm ơn nha

**Comment by TrungKien1508** [comment]
tui cũng làm đc rồi

**Comment by DuyThanh36** [comment]
![Uploading Screenshot (129).png…]()

**Comment by DuyThanh36** [comment]
Ok r nha mn

**Comment by DuyThanh36** [comment]
![Screenshot (130)](https://user-images.githubusercontent.com/91962681/141672053-e2f2fcfe-5aa6-4da0-a6a1-8eef05fa6559.png)

**Comment by DuyThanh36** [comment]
![Screenshot (131)](https://user-images.githubusercontent.com/91962681/141672081-47854bf6-743a-4c70-86b3-4c342d0224bd.png)

**Comment by DuyThanh36** [comment]
V mn nghỉ nha

**Comment by DuyThanh36** [comment]
Cảm ơn mn nhiều

**Comment by TrungKien1508** [comment]
okok

**Comment by TrungKien1508** [comment]
bái bai mn
