### ISSUE TITLE
Phần 1: Hãy cho biết số thự tự dòng lệnh thuộc về phần "KHAI BÁO" (Khai báo Thư viện, Hằng, Biến)

### ISSUE THREAD

**Issue by DuyThanh36** [DuyThanh36/Lop-11A09-Nhom-01#2]
Mọi người nhớ ghi số thứ tự kèm dòng code kế bên (Nếu có thể).

**Comment by TrungKien1508** [comment]
PHẦN 1: KHAI BÁO
Khai báo thư viện: 01 #include <SoftwareSerial.h>
Khai báo hằng: 02 #define BT_TRAIN 2
                          03 #Define BT RECEI 3
Khai báo biến: 06 int relay = 10;
