### ISSUE TITLE
Phần 2: Hãy cho biết số thứ tự dòng lệnh thuộc về phần "THIẾT LẬP"

### ISSUE THREAD

**Issue by DuyThanh36** [DuyThanh36/Lop-11A09-Nhom-01#4]

**Comment by hung0705** [comment]
PHẦN 2: THIẾT LẬP
08 void setup ()
09 {
10  pinMode (relay, OUTPUT);
11  BlueTooth.begin(9600);
12 }

BlueTooth.begin(9600); :Dùng để truyền dữ liệu từ board Arduino lên máy tính.

pinMode (relay, OUTPUT); // Chân relay là ngỏ ra

**Comment by hung0705** [comment]
@
