### ISSUE TITLE
Cho biết sự khác nhau giữa hàm void setup() và void loop()

### ISSUE THREAD

**Issue by DuyThanh36** [DuyThanh36/Lop-11A09-Nhom-01#6]

**Comment by ThienPhuc33** [comment]
Void setup()
Các câu lệnh thiết lập:
Các tốc độ truyền dữ liệu:
+ Serial.begin(9600)Dùng để truyền dữ liệu từ board Arduino lên máy tính.
pinMode(biến, kiểu vào hoặc ra);
 Dùng đểxác định kiểu chân là vào hay ra
Ví dụ:
pinMode(button, INPUT); //  Chân button là ngỏ vào
pinMode(ledPin, OUTPUT);//  Chân ledPin là ngỏ ra

Void loop() Các câu lệnh điều khiển thiết bị để mạch Arduino thực hiện các nhiệm vụ mà chúng ta mong muốn.
Một số kí hiệu thường gặp:
//     Dùng để chú thích, khi nội dung chú thích nằm trên 1 dòng
/*      Dùng để chú thích, nhưng chú 
......    thích dành cho 1 đoạn
*/
Delay(thời gian);   Lệnh này dùng để duy trì trạng  thái đang thực hiện chờ một thời gian
Serial.print();  In ra màn hình máy tính (Serial Monitor), lệnh này in không xuống dòng. VD: Xem bài TH1
Serial.println();   In ra màn hình máy tính, in xong xuống dòng, giá trị tiếp theo sẽ được in ở dòng kế tiếp.VD: Xem bài TH1
digitalRead(chân);
-Chức năng: đọc giá trị từ các chân tín hiệu digital, trả về giá trị là HIGH hoặc LOW.
  +Chân được đọc phải đư ợc thiết lập là INPUT bằng lệnh pinMode trước khi đọc tín hiệu.
  +Chân đầu vào thiết bị phải đư ợc găm vào chân digital 1-->13
digitalWrite(chân, trạng thái); 
-Chức năng: Viết (xuất) giá trị từ các chân tín hiệu digital, giá trị có thể là HIGH hoặc LOW.       +Chân ra phải được thiết lập là OUTPUT bằng lệnh  pinMode trước khi xuất tín hiệu.
 +Chân ra thiết bị phải được găm vào chân digital 1-->13

**Comment by DuyThanh36** [comment]
Tốt, Very Tốt.
